name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: "9.x"

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore backend/app.sln

      - name: Build
        run: dotnet build backend/app.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test backend/app.sln --configuration Release --no-restore --no-build

      - name: Publish
        run: dotnet publish backend/app.sln --configuration Release --no-restore --no-build

  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/app
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test (if available)
        run: |
          if npm run | grep -qE '^ *test:'; then npm test; else echo "No test script"; fi

      - name: Preview (optional)
        run: npm run preview &
        continue-on-error: true
